---
title: "Fit CII Model - Thinned"
author: "William Ruth"
output: 
  pdf_document
---


```{r packages, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)


library(knitr)
library(dplyr)
library(magrittr)
library(ggplot2)
library(gridExtra)
library(purrr)
library(tibble)
library(ggfortify) # ggplot version of regression diagnostics
library(latex2exp) # Use latex for plot labels with the TeX() function
library(xtable)    # Create latex tables
```


```{r setup, include=FALSE, cache=TRUE}
num_students <- 17038


data <- read.csv("D:/School/Thesis/COVID_Network_Julia/Data/Output/Thinned/All_Outbreak_Sizes.csv")

num_trials = nrow(data)

# Number of students remaining in the network for each threshold level
network_sizes <- c(16675, 22715, 24041)

all_thresholds <- unique(data$threshold)

thresh2size <- function(thresh){
  if(thresh == 20){
    network_sizes[1]
  } else if(thresh == 50){
    network_sizes[2]
  } else if(thresh == 100){
    network_sizes[3]
  } else{
    stop("Invalid threshold level.")
  }
}

for (i in 1:(ncol(data)-1)) {
  data[, i] <- factor(data[, i])
}

for (i in 1:(ncol(data)-2)) {
  levels(data[,i]) <- c("low", "med", "high")
}



get_formula <- function(resp_var, control_var, data, int = TRUE){
  model_vars = data %>%
    select(-!!resp_var, -!!control_var) %>%
    names()
  
  # First-order terms
  (form_str <- paste(model_vars, collapse = " + "))
  (form_str <- paste(control_var, form_str, sep = " + "))
  (form_str <- paste(resp_var, form_str, sep = " ~ "))
  
  # Second-order terms. Only include interactions with the control variable
  if (int) {
    (form_int_str <- paste(model_vars, control_var, sep = "*"))
    (form_int_str <- paste(form_int_str, collapse = " + "))
    (form_str <- paste(form_str, form_int_str, sep = " + "))
  }
  
  # Convert string to formula object
  form = formula(form_str)
  
  form
}

data$network_size <- sapply(data$threshold, thresh2size)

data_logit <- data %>% 
  mutate(prop = size / network_size) %>% 
  select(-size, -network_size)

```


## Marginal Behaviour of Each Predictor ##

The following figure gives a sequence of boxplots for the CII in our simulation. Each plot corresponds to a single predictor, and each box contains all simulation runs with that level of the predictor.

```{r Boxplot_Grid}
var_names <- variable.names(data_logit)[1:9]
var_labels <- c(TeX("$\\rho_A$"), TeX("$\\rho_{I1}$"),
  TeX("$\\theta_{I2}$"), TeX("$q_E$"), TeX("$q_A$"),
  TeX("$q_{I1}$"), TeX("$q_{I2}$"), TeX("$q_{EA}$"), 
  TeX("$\\phi$")
  )

base_boxplot <- ggplot(data_logit, aes(y = prop))
all_boxplots <- list(1:9)
for(i in 1:9){
  this_plot <- base_boxplot +
    geom_boxplot(aes_string(x = var_names[i])) +
    xlab(var_labels[i]) + ylab("CII")
  all_boxplots[[i]] <- this_plot
}
grid.arrange(grobs = all_boxplots, ncol=3)
plot(all_boxplots[[9]])
```
